version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel_app
    ports:
      - "80:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: bgypvyun3ifoinznj3v4-mysql.services.clever-cloud.com
      DB_PORT: 3306
      DB_DATABASE: bgypvyun3ifoinznj3v4
      DB_USERNAME: usqesj0cnciqcnol
      DB_PASSWORD: 69XchqnzGRQWpnhglPif
