version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel_net
    # Asegúrate de que tus variables de entorno estén definidas
    # o usa un archivo `.env` dentro del contenedor para conectar a la BD externa

networks:
  laravel_net:
    driver: bridge
