version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel_net
    environment:
      # Variables para conectar a base de datos externa (ajusta según sea necesario)
      DB_CONNECTION: mysql
      DB_HOST: tu_host_bd_externo
      DB_PORT: 3306
      DB_DATABASE: tu_base_de_datos
      DB_USERNAME: tu_usuario
      DB_PASSWORD: tu_contraseña

networks:
  laravel_net:
    driver: bridge
